### ISSUE TITLE
Add site favicon in full items mode

### ISSUE THREAD

**Issue by Keith94** [brief-rss/brief#210]
When "View full items" view is turned on, there is no longer a favicon displayed for any entries, like it does for "headlines view". Maybe it would be a nice addition to also have a favicon next to the feed name or the headline name.

For example for the two entries below, I couldn't tell which of the two feeds they belong to at a glance, and having an icon would help differentiate them.

![snag 2016 09 23 07 13 55](https://cloud.githubusercontent.com/assets/5490615/18788949/c6b4859c-815d-11e6-8bb9-ea730b7e9be3.png)

**Comment by tanriol** [comment]
@Keith94 By mass closing bugs do you mean "seems to be fixed" or "no longer interested in these"?

**Comment by Keith94** [comment]
The latter, I guess. They've spanned too long a time period. :P
