### ISSUE TITLE
indexedDB needs to be enabled for Brief to work?

### ISSUE THREAD

**Issue by Radagast** [brief-rss/brief#303]
As the title suggests. In my main browser I have indexdDB disabled and when Brief is installed none of the menu items work. Re-enabling indexdDB allows access to these items. 

I also block cookies, so I added an exception to firefox for the Brief UUID, in the same way I do for other webextensions that require this but that alone wasn't enough to make Brief work.

**Comment by tanriol** [comment]
Yes, IndexedDB is required. It's the only storage mechanism I know available to WebExtensions that can store thousands of entries Brief needs to store.

**Comment by Radagast** [comment]
Thanks for the reply. Out of interest, why doesn't brief place an entry in {profile}/Storage/Default as extensions such as uBO/uMatrix etc., do?

**Comment by tanriol** [comment]
Due to compatibility reasons and persistence APIs available, the Brief's data for now lives in `$profile/storage/permanent`, not default.

**Comment by Radagast** [comment]
Thanks for explaining, I have a better understanding now.
