### ISSUE TITLE
Brief is not compatible with sanitizeOnShutdown pref

### ISSUE THREAD

**Issue by lunatigs** [brief-rss/brief#306]
When Brief gets updated it works exactly once (and pretty well so far), but then it stops.
When i open Brief again Firefox asks me for permission if i want to allow Brief to store data (once per browser session).
Even if i do allow that, Brief won't start fetching anything. Not when i press the update button on top, not when i hit update for each feed individually.

I don't know if that's a bug of Brief or a bug of Firefox or a bug of Firefox in combination with my system (linux), just thought it won't hurt if i do report it.

**Comment by tanriol** [comment]
Sounds rather strange. Do you use any nonstandard / restrictive privacy settings? Any messages from Brief in the browser console when you cannot start an update?

**Comment by FatOrangutan** [comment]
This might be [Bug 1416219](https://bugzilla.mozilla.org/show_bug.cgi?id=1416219). @lunatigs, do the three conditions in [comment 7 there](https://bugzilla.mozilla.org/show_bug.cgi?id=1416219#c7) hold true for you? (FWIW, I'm running into this same issue on Nightly)

**Comment by lunatigs** [comment]
@FatOrangutan exactly - i switched **privacy.sanitize.sanitizeOnShutdown** to **false**, restarted Firefox and now Brief has come back to life.
But i hope that's not the solution, cause i definitively won't leave that switched off.
Anyway, as a temporary solution it's good to know.

**Comment by tanriol** [comment]
This seemingly has been fixed in Firefox years ago.
