### ISSUE TITLE
brief not working at all

### ISSUE THREAD

**Issue by focusonjoy** [brief-rss/brief#322]
i have not been able to use any of the brief 2.5 series - trying to load any rss feed from any website always gives this response:

Firefox can’t find the file at chrome://brief/content/brief.xhtml?subscribe=https://jayarava.blogspot.com/feeds/posts/default?alt=rss.

are there any specific conditions that need to be set in FF for brief to function ?

please advise
windows 10
FF 57
brief 2.55

and thanks for what you're doing, tanriol !!

**Comment by tanriol** [comment]
Do you have unusually strict privacy settings?

**Comment by focusonjoy** [comment]
dear denis

thanks for writing !

prior to FF57 i  (successfully) used the setting 'never remember history' -
with FF57 i have used all three of the history options, without success

otherwise i have not adjusted FF settings...

are there specific settings that we should use with brief?

best wishes
david white

**Comment by tanriol** [comment]
@focusonjoy Brief currently cannot support "Never remember history" and (as far as I know) does not work correctly with "Always private browsing", with "Clear history when Firefox closes" or without "Accept cookies from websites", as with these options Brief either cannot open the IndexedDB to store feeds and entries, or loses the data on restart.

**Comment by focusonjoy** [comment]
as i said in my last email, i have tried all three of the history options
in FF57

and if i understand you correctly, the only option now available is
'remember history', which still does not work

i have emptied history, and tried safe mode

( is it useful information to tell you that i can add rss feeds to the
bookmarks toolbar...?)

and i found a generic discussion of problems with rss feeds and ff57, which
may mean more to you:

https://support.mozilla.org/en-US/questions/1189965

thank you!

**Comment by tanriol** [comment]
> as i said in my last email, i have tried all three of the history options in FF57

It works with "Remember history" or with some (but not all) custom settings. The rest depends on Mozilla fixing some bugs.

If it does not work after you change the settings to "Remember history" and restart Firefox, please help me debug it with the following:
 - disable Brief,
 - open the browser console,
 - clear it,
 - enable Brief again,
 - wait a minute,
 - post any startup messages from Brief that appeared in the console here.

> ( is it useful information to tell you that i can add rss feeds to the bookmarks toolbar...?)

> a generic discussion of problems with rss feeds and ff57

Not applicable, Brief no longer has any access to Live Bookmarks.

**Comment by NgoHuy** [comment]
You must allow tracking protection only on private tab, some website not work in brief if tracking protection is set to always (eg reddit,blogpost,...)

**Comment by focusonjoy** [comment]
did as you asked, no success, and got this in the browser console:

Error: Could not establish connection. Receiving end does not exist.
undefined
No chrome package registered for
chrome://brief/content/brief.xhtml?subscribe=
https://www.thesimpledollar.com/home/feed/
Error: Message manager disconnected  undefined
No chrome package registered for
chrome://brief/content/brief.xhtml?subscribe=
https://www.thesimpledollar.com/home/feed/
Error: Could not establish connection. Receiving end does not exist.
undefined
[Exception... "Component returned failure code: 0x80070057
(NS_ERROR_ILLEGAL_VALUE) [nsIMessageSender.sendAsyncMessage]"  nsresult:
"0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 505"
data: no]  (unknown)
moz-extension://74864d2b-714e-423a-91bf-07f12fd5bb0e/background.html:
chrome tabs query did not return a result while changing window focus

**Comment by minno726** [comment]
I'm still experiencing this. One thing I've noticed is that the error message says "Firefox can’t find the file at ```chrome://brief/content/brief.xhtml?subscribe=```...", while the extension itself is located at "```moz-extension://95579e6c-d7e3-4bf0-b4e0-453cfed6a7b3/ui/brief.xhtml```" when I open the feeds page. Could this mismatch be what's causing the problem? I tried replacing ```/ui/brief```... with the corresponding segment from the error message's url, but that didn't work.

**Comment by minno726** [comment]
I am no longer experiencing this issue.

Windows 10
Brief 2.5.7
Firefox 60.0.1

**Comment by tanriol** [comment]
Looks like this bug used to be about lack of support for the old Brief subscribe URLs, which was added in 90ef4c8950b7b60f3ba0733f50bc97430a00b90b. Closing.
