### ISSUE TITLE
Can't export feeds - nothing happens on clicking export feeds

### ISSUE THREAD

**Issue by Sam-De** [brief-rss/brief#324]
Can't export feeds - nothing happens on clicking export feeds
Error message in browser console

TypeError: str is undefined[Learn More]  opml.js:110:13

**Comment by tanriol** [comment]
Looks interesting... a feed without `title`, `feedURL` or `websiteURL`. Thank you for reporting!

**Comment by Sam-De** [comment]
All feeds have a name and location (checked feed settings) ... if that's what you are referring to
