### ISSUE TITLE
Subscribing to a new feed via URL only?

### ISSUE THREAD

**Issue by VillageCatDad** [brief-rss/brief#327]
I've been digging around, but I'm stumped.  How do I subscribe to a new feed when the site only provides the feed URL?  If I visit the actual content page, the "subscribe" toolbar button is greyed out.  But if I navigate to the site's RSS info page, they provide a URL which works in FF, but I can't figure out a way to update the entry in brief to point to the new URL.  If I select Feed Settings, I can't edit the URL, only the description.

**Comment by tanriol** [comment]
Could you please show an example of such a feed?

**Comment by VillageCatDad** [comment]
Here's the blog site:  https://www.military.com/defensetech

When I go there, the RSS button in my FF tool bar is greyed out.

If you scroll down to the page's footer, you'll find an RSS link, which takes you to a page with all the site's RSS feeds.  But when you click on one, FF asks you to subscribe the usual way.  But I want to put that subscription into Brief, not FF Live Bookmarks.

In Brief, I think I would like to be able to right click on the "Feed Settings" for that specific feed, and edit the URL ("Location").  But I can't.

**Comment by tanriol** [comment]
> But when you click on one, FF asks you to subscribe the usual way.

Note that on that page you can select Brief to subscribe using Brief. Also, there's a Brief icon in the URL bar to subscribe to them.

**Comment by VillageCatDad** [comment]
Ok, that's fixed it.  Would be nice to have a little UI feedback when clicking on the Brief subscribe button in the URL bar.  There's nothing, so have to go back to Brief to see if the feed has shown up at the bottom of my feed list.
