### ISSUE TITLE
cannot subscribe to feeds on addons.mozilla.org

### ISSUE THREAD

**Issue by n8v8R** [brief-rss/brief#334]
FF 57.0.2 (64-bit) with B 2.5.5 on W10 x64 b16299 

Brief Subscribe icon on the address is a no show.

on the actual feed page [https://addons.mozilla.org/en-US/thunderbird/extensions/format:rss?sort=updated](https://addons.mozilla.org/en-US/thunderbird/extensions/format:rss?sort=updated) Brief is a no show again

![capture](https://user-images.githubusercontent.com/13611490/34417061-c8a47eca-ebf6-11e7-9838-915910457028.PNG)

**Comment by tanriol** [comment]
This is a known problem. `addons.mozilla.org` is blacklisted for WebExtensions, so Brief cannot integrate into the subscribe page or see the content of the extension page. Some workaround is needed.

**Comment by n8v8R** [comment]
Perhaps if there were an option in Brief to manually add feeds by url, e.g. [https://addons.mozilla.org/en-US/thunderbird/extensions/format:rss?sort=updated](https://addons.mozilla.org/en-US/thunderbird/extensions/format:rss?sort=updated)

**Comment by tanriol** [comment]
I'm not closing this as the problem is known, but not fixed.

**Comment by n8v8R** [comment]
sure, I just hit the wrong button...

**Comment by n8v8R** [comment]
Out of curiosity I played with the `about:config` and edited those silly old Yahoo handlers to:

`browser.contentHandlers.types.0.title` `Brief`
`browser.contentHandlers.types.0.uri` `moz-extension://23cd4e0a-9a8a-4176-adcd-9a6b8fa27db6/ui/brief.xhtml`

Which, after restarting the browser logically shows **Brief** as opposed **My Yahooo**

![capture](https://user-images.githubusercontent.com/13611490/34421920-9e7b43e2-ec12-11e7-8775-2f3dac025dd5.PNG)

Clicking on **Subscribe Now** then also opens Brief (if not already open) but it does not subscribe to the feed though :(

**Comment by Antagony1060** [comment]
I posted [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1443860) on Bugzilla but they're saying it's a duplicate of [another bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1356397) and I think it's probably related to this issue. 

I'm not sure if this problem is Mozilla's or this add-on's, but it's frustrating there is no obvious way to make subscribing to a feed default to Brief, instead of being forced through the preview and having to pick Brief from the drop-down list every time.

**Comment by tanriol** [comment]
There seems to be a possible [workaround](https://bugzilla.mozilla.org/show_bug.cgi?id=1445663#c3) using a trailing dot in the domain name.

**Comment by n8v8R** [comment]
nice find. fingers crossed

**Comment by n8v8R** [comment]
Got it working by disabling the mozAddonManager Web API via `about:config`:

FF 57+
sanitize/clear `extensions.webextensions.restrictedDomains`

FF60+
https://bugzilla.mozilla.org/buglist.cgi?bug_id=1384330,1406795,1415644,1453988

`privacy.resistFingerprinting.block_mozAddonManager", true` (which is a _hidden_ preference)
