### ISSUE TITLE
Brief 2.5.5 not responding in FF 57+ on Mac OSX 

### ISSUE THREAD

**Issue by MichaelKreuzer** [brief-rss/brief#335]
The current version of Brief (2.5.5) is unfortunately not working in FF 57+ on Mac OSX. 
I encountered this problem on Mac OSX High Sierra, 10.13.2 and also on some previous version.

It seems like windows versions are ok, due to the comments in the public Firefox Addon Directory (https://addons.mozilla.org/de/firefox/).

More detailed description of the bug:
-Brief-addon can be installed successfully
-Brief can be opened
-Brief shows all the links /buttons, like: update, organize, preferences, show all etc.
-If I click on the links, nothing happens

The Firefox developer console shows the following:
Brief: opening database in persistent storage          database.js:43:9
InvalidStateError                                                         database.js:48:21

#### Remark ####
I uploaded a .zip-File that has to be renamed to .mp4. This is due to the restrictions of file-uploads on github. The video shows what happens on my computer, including all my mouse clicks. I hope that helps.

**Comment by ebrowne72** [comment]
I'm also seeing this. FF 58.0.1, MacOS 10.12.6.

**Comment by tanriol** [comment]
@MichaelKreuzer @ebrowne72 

Any nonstandard settings (privacy / cookies / isolation / something else like this)? The error above means Brief cannot access its database. Unfortunately, without any details.

**Comment by tanriol** [comment]
Closing as there's not enough data here to actually do anything. Brief needs better error reporting, but there's #527 for that.
