### ISSUE TITLE
Document the rationale for each permission

### ISSUE THREAD

**Issue by foobuzz** [brief-rss/brief#358]
Hello,

So I just realized that Brief was working on the new WebExtension system, thank you for the work on that!

When I installed it, it asked for a bunch of permissions, that can be seen in [manifest.json](https://github.com/ancestorak/brief/blob/7bda3e9130ef2bcfa77a034db8c46dad58d8677c/manifest.json). It would be nice to have a breakdown of what functional purpose serves each one of those permissions, especially those which aren't obvious (downloads?). Such documentation could be somewhere like in the README.

**Comment by bdcomp** [comment]
Even better place for this will be the add-on description on AMO, so it will be clear before installing/downloading.

**Comment by tanriol** [comment]
Documented in the README since 4bc54c583520f62cca381a67a0e4e3.
