### ISSUE TITLE
Brief 2.5.6 fails to upgrade the database

### ISSUE THREAD

**Issue by tanriol** [brief-rss/brief#363]
Reported [by @mukinstein](https://github.com/brief-rss/brief/issues/355#issuecomment-392587020)

> After opening the Developer Tools the first thing displayed is:
> 
> Brief: opening database in default storage database.js:135:9
> TypeError: this._db is null[Learn More] database.js:301:13
> The database in default storage needs upgrade, aborting database.js:161:21
> 
> After trying: "indexedDB.open('brief', 100).onupgradeneeded = ev => { console.log("Old version:", ev.oldVersion); throw "abort" };
> 
> I get back:
> Old version: 20 debugger eval code:1:56
> uncaught exception: abort

**Comment by voxik** [comment]
I have the same experience. I just came back to my computer to see that I have not feed. Yesterday I was reading the news just fine. Please note that I have not restarted computer nor FF in between.

I restarted FF now and the about:debugging says:

```
Brief: opening database in persistent storage  database.js:135:9
Brief: opened database in persistent storage  database.js:166:9
Brief: prev database has 64 feeds and 78623 entries  database.js:70:17
Brief: opening database in default storage with upgrade  database.js:135:9
Brief: opening database in default storage  database.js:135:9
Brief: opening database in default storage  database.js:135:9
```

**Comment by mukinstein** [comment]
This is what I get:

Error: Could not establish connection. Receiving end does not exist. RequestGuard.js:280:7
pendingRequests.get(...) is undefined  RequestGuard.js:435
Error: Could not establish connection. Receiving end does not exist. RequestGuard.js:280:7
Error: Invalid tab ID: -1 ext-browser.js
Error: Could not establish connection. Receiving end does not exist. RequestGuard.js:280:7
Error: Invalid tab ID: -1 ext-browser.js
Error: Could not establish connection. Receiving end does not exist. RequestGuard.js:280:7
Error: Invalid tab ID: 45 ext-browser.js
Error: Could not establish connection. Receiving end does not exist. RequestGuard.js:280:7
TypeError: this.contentWindow is null[Learn More]  ExtensionPageChild.jsm:191:5
Error: Could not establish connection. Receiving end does not exist.  main.js:120:10
No matching message response handler for 687194777477  MessageChannel.jsm:1011
Error: Could not establish connection. Receiving end does not exist. RequestGuard.js:280:7
Error: Invalid tab ID: 53 ext-browser.js
Error: Could not establish connection. Receiving end does not exist. RequestGuard.js:280:7
Error: Invalid tab ID: 51 ext-browser.js
Error: Could not establish connection. Receiving end does not exist. RequestGuard.js:280:7
Brief: opening database in persistent storage  database.js:135:9
The ‘storage’ attribute in options passed to indexedDB.open is deprecated and will soon be removed. To get persistent storage, please use navigator.storage.persist() instead.  database.js:145:21
Brief: opened database in persistent storage  database.js:166:9
Brief: prev database has 263 feeds and 62020 entries  database.js:70:17
Brief: opening database in default storage with upgrade  database.js:135:9
Upgrading from version 20  database.js:183:13
Brief: starting migration from Object { name: "persistent", db: IDBDatabase, feeds: Array[263], count: Object }  database.js:1491:9
uncaught exception: Brief: migration into already-used database not yet supported  (unknown)
TypeError: this._db is null[Learn More]  database.js:301:13
Brief: opening database in default storage  database.js:135:9
The database in default storage needs upgrade, aborting  database.js:161:21
TypeError: this._db is null[Learn More]  database.js:301:13

**Comment by tanriol** [comment]
> Brief: migration into already-used database not yet supported (unknown)

Ok, I was too optimistic to assume that no one will have this problem. This is not the first time you lose your feeds, correct?

**Comment by mukinstein** [comment]
Yes, it happened before (I don't recall how long it's been now), but when I restarted Firefox it was back to normal.

**Comment by tanriol** [comment]
@voxik So it does not actually say "opened database in default storage", does it?

**Comment by voxik** [comment]
@tanriol no.

**Comment by voxik** [comment]
Actually now I see:

~~~
TypeError: this._db is null[Zjistit více]
database.js:301:13
~~~

In debug console.

**Comment by voxik** [comment]
I jsut downgraded to 2.5.5 and my feeds are back.

**Comment by tanriol** [comment]
@mukinstein I do understand your problem and will try to fix it in a day or two in 2.5.7.

@voxik In your case I don't understand what could cause it to hang opening the database in "default" storage.
Does the following snippet in a Brief tab's debugging console print anything at all?
```
indexedDB.open('brief', 100).onupgradeneeded = ev => { console.log("Old version:", ev.oldVersion); throw "abort" };
```

**Comment by Mikolaj** [comment]
I have

```
Brief: opening database in default storage
database.js:135:9
Brief: opened database in default storage
database.js:166:9
Brief: 463 feeds in database
database.js:304:9
Brief: opened database with 0 entries
database.js:89:9
```

and downgrading to 2.5.5 didn't help. BTW, thank you for your work, very appreciated.

**Comment by saffroy** [comment]
Same problem here, found all Brief feeds gone this morning after it upgraded itself to 2.5.6. As suggested above (thanks!), I could see my feeds again by downgrading Brief to 2.5.5: go to https://addons.mozilla.org/en-US/firefox/addon/brief/versions/ then scroll to 2.5.5 and "Add to Firefox".

**Comment by voxik** [comment]
It does not provide any meaningful output as far as I can tell:

~~~
>> indexedDB.open('brief', 100).onupgradeneeded = ev => { console.log("Old version:", ev.oldVersion); throw "abort" };
function ()
~~~

**Comment by voxik** [comment]
I hve not mentioned my FF version yet:

~~~
$ rpm -q firefox
firefox-60.0-6.fc29.x86_64
~~~

I realized may be I should, since on different computer, with FF 60.0.1, latest Brief works just fine.

**Comment by tanriol** [comment]
@mukinstein, @saffroy 
I expect that Brief 2.5.7 fixes the problem for you. Please tell me if it does not.

@voxik 
If 2.5.7 is still bad for you, could you please check whether there's a folder
```
${firefox_profile}/storage/default/moz-extension+++${brief_uuid}/idb
```
and whether moving it from there to any other place allows Brief to start and migrate data normally. If it does not, please open a follow-up issue.

**Comment by Mikolaj** [comment]
It now works for me. Thank you!

**Comment by mestaritonttu** [comment]
Thank you very much, I was affected and now my feeds are back :)
