### ISSUE TITLE
new feeds do not appear

### ISSUE THREAD

**Issue by kodabb** [brief-rss/brief#371]
Apologies if this is a duplicate of 368, but adding new feeds (via the Subscribe using Live Bookmarks) does not seem to work. I seem to remember that it was sufficient to add feeds to the special "Subscribed Feeds" folder, is the process changed?

**Comment by tanriol** [comment]
Since Firefox 57, extensions have no access to Live Bookmarks. I have some hope for this changing, but for now the correct method of subscribing is to use the Brief icon in the address bar or to use the "Brief" entry in the "Subscribe using" dropdown if you have one left since previous versions.

**Comment by kodabb** [comment]
ah indeed, the brief icon in the address bar works
should this issue be closed then?
thanks
