### ISSUE TITLE
FF 61.0.1 - Brief ceased working and all feeds gone

### ISSUE THREAD

**Issue by n8v8R** [brief-rss/brief#377]
FF 61.0.1 (64-bit)
Brief 2.5.8
Win 10 Pro 1709 b16299.522

Having closed FF with Alt + F4 and restarted FF Brief then ceased working and all feeds are gone.

Removed Brief, restarted FF, installed Brief and still nothing, restarted the browser and still nothing.
Clicking Options in the feed pane does nothing.
Subscribing to feeds is not working either.

> Brief: opening database in default storage database.js:135:9
> Error opening database: UnknownError The operation failed for reasons unrelated to the database itself and not covered by any other error code. database.js:164:17
> _open
> moz-extension://97ead1a9-ea9e-4ae4-b339-6c545529b7ba/scripts/database.js:164:17
> 20:12:51.414 TypeError: this._db is null[Learn More]

**Comment by n8v8R** [comment]
Downgraded to Brief 2.5.5 and it works again albeit stored feed content is gone :( but at least the feedlist remained intact.

Tried upgrading to 2.5.6, 2.5.7 and 2.5.8 and none is working -> feedlist is empty and drop down from Options in the feed panel does nothing.

Like so many other reports this happened out of the blue. What I did prior closing the browser with Alt + F4 was cleaning browser data via `about:preferences#privacy` :+1: 

1. Clear All History with Time Range Everything and all Details except Site Preferences
2. Clear Data with both items checked

Neither should have touched the Brief db but may have, although only apparent after the browser been restarted. 
Why though the feedlist is retained but not the content is strange as is 2.5.5 working but anything later released not alabeit having worked prior to the browser's restart

**Comment by tanriol** [comment]
Could you please tell me what does `https://firefox-storage-test.glitch.me/` tell you (not in private mode)?

> Error opening database: UnknownError

It may be that your IndexedDB got unexpectedly broken... that happens sometimes with Firefox.

> Removed Brief, restarted FF [...] stored feed content is gone

Firefox drops the extension storage, except for the sync storage, when you completely uninstall it (probably on next restart).

> Downgraded to Brief 2.5.5 and it works [...] upgrading to 2.5.6, 2.5.7 and 2.5.8 and none is working

So the "persistent" storage does work (but has been cleared) while the "default" one seems to not work at all.

> Why though the feedlist is retained but not the content is strange

There's a feedlist backup in the "sync" storage, which does not get cleared on uninstall.

> What I did prior closing the browser with Alt + F4 was cleaning browser data via `about:preferences#privacy`

Have you, by any chance, opened the Firefox profile folder with a file manager (e.g. Explorer) while Firefox was open in that session? Maybe tried to do something there? One known cause of storage problems in Firefox is unexpected files in the storage folders, which some file managers can leave even when just browsing the folders.

**Comment by n8v8R** [comment]
Indexed Database API is blocked, hence it would not work with a website like https://firefox-storage-test.glitch.me/

> LocalStorage
>     Good: Totally Working. (fullyOperational)
> QuotaManager
>     Bad: Totally Broken. (fullyBroken)
> IndexedDB
>     Bad: Totally Broken. (fullyBroken)
> Cache API
>     Bad: Totally Broken. (fullyBroken)
> 
> Debug Info:
> 
> storage.estimate() threw: The expression cannot be converted to return the specified type.
> Failed to create "persistent" IDB.
> Failed to create "transient" IDB.
> 
> {
>   "v": 1,
>   "curVersion": 60,
>   "prevVersion": 60,
>   "ls": {},
>   "qm": {
>     "lastWorkedIn": 0
>   },
>   "idb": {
>     "persistentCreatedIn": 0,
>     "persistentLastOpenedIn": 0,
>     "clearDetectedIn": 0
>   },
>   "cache": {
>     "firstCacheCreatedIn": 0,
>     "unpaddedOpaqueCreatedIn": 0,
>     "paddedOpaqueCreatedIn": 0
>   }
> }

---

> IndexedDB got unexpectedly broken... that happens sometimes with Firefox

Don't you think it is curious this being reported by Brief users here, happening out of the blue?

> while the "default" one seems to not work at all.

Well, it did well enough prior this incident and now it is not anymore. Like stated removed Brief, restarted the browser, reinstalled, even rebooted the entire box but to no avail.

> Have you, by any chance, opened the Firefox profile folder with a file manager (e.g. Explorer) while Firefox was open in that session? Maybe tried to do something there? 

Nothing at all. I rather suspect that the date cleaning caused this, perhaps the "default" storage is include in the purge. But that it does not return seems more of a bug.

**Comment by tanriol** [comment]
> Don't you think it is curious this being reported by Brief users here, happening out of the blue?

Up to Brief 2.5.5 only the "persistent" storage was used for Brief. In 2.5.6 the migration to the "default" one landed as the "persistent" storage will be completely dropped in a few Firefox releases. Unfortunately, the "default" one has some more failure modes related, in particular, to the Quota Manager component. Most bug reports are likely to be caused by this problem.

> Indexed Database API is blocked

Do you mean you've disabled it in some way, or that it's not available for some reason you don't know?

**Comment by n8v8R** [comment]
It is disabled though this extension https://addons.mozilla.org/en-GB/firefox/addon/webapi-manager/ and had never been an issue with Brief.

**Comment by n8v8R** [comment]
`/storage/default/moz-extension+++${brief_uuid}/idb` is not existent on this installation. instead there is a folder `moz-extension+++7bcd14bb-9a8b-46f0-bd2c-39b33a0821b1` which apparently corresponds to `moz-extension://7bcd14bb-9a8b-46f0-bd2c-39b33a0821b1/ui/brief.xhtml`

Absent from that folder `moz-extension+++7bcd14bb-9a8b-46f0-bd2c-39b33a0821b1` however is `idb` whilst being present in other sub directories of `/storage/default/`

**Comment by ruipin** [comment]
If I delete the storage folder for Brief, I get exactly the same situation. The UI seems frozen, and I get the " TypeError: this._db is null" error.

**Comment by ruipin** [comment]
Hmm, after playing around with the profile quite a bit, deleting the folder "storage/permanent/moz-extension+++<uuid>" and not touching "storage/temporary" seems to have unstuck Brief and everything is working again.

**Comment by n8v8R** [comment]
Did not work for me. Seems I am stuck with either Brief 2.5.5 or have to switch another feed reader

**Comment by ruipin** [comment]
If I deleted the storage/temporary folder as well, it did not work. I had to use my backup of that folder, only deleting the storage/permanent folder.

But my initial issue was different - I could not refresh or modify my feeds list. I only got the same issue when I deleted the storage/temporary folder for Brief.

**Comment by Mikolaj** [comment]
Removing the storage directories nor main cache folders didn't help me, but removing the broken sqlite caches did: https://github.com/mozilla/notes/issues/512#issuecomment-363822635

**Comment by n8v8R** [comment]
@Mikolaj Thank you for the input. Unfortunately it did not solve it this end.

**Comment by n8v8R** [comment]
Meantime migrated to 63.0a1 (2018-08-19) (64-bit) with a fresh profile (and Win 10 Pro 1803 b17134.228) and this issue has vanished.
