### ISSUE TITLE
Feeds preview

### ISSUE THREAD

**Issue by lisandrodemarchi** [brief-rss/brief#380]
As many RSS readers do, it would be great if clicking the awesome bar icon to add an RSS feed, instead of adding it directly, shows a preview in Brief of the latest five or so articles. There should be a button to confirm the addition maybe with an option to select the destination folder/category, or cancel the operation altogether.
Rationale:
Many websites have broken or empty feeds (the typical example are sites made with Wordpress that only use the "Pages" function but still have an autodiscovery link). Other sites links from every page to the general feed and not to the specific category/topic/user/whatever we are viewing in the browser (Behance for example).
The only option available now is to add the feed, then review it and put it in the corresponding folder or delete it.
As a workaround I am currently using the built in RSS preview feature in Firefox ( with the "Awesome RSS" extension ) but Mozilla has [just announced][1] they gonna axe Live Bookmarks and RSS preview functionality in an upcoming version.

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1477667

**Comment by tanriol** [comment]
Preliminary preview implemented in 2d3d560 and follow-ups.
