### ISSUE TITLE
Brief no longer works with FF 61.0.2

### ISSUE THREAD

**Issue by Pienamics** [brief-rss/brief#386]
Removed, re-installed and, eventually, it started working again.  This can be losed.

**Comment by Pienamics** [comment]
I tried removing and re-installing Brief and now it doesn't run at all.  There's a blank on the toolbar where the icon should be but nothing happens when I press it - other than the icon going the darker grey to show that it's been pressed.  

FF 61.0.2 on a Mac running 10.11.6.

**Comment by tanriol** [comment]
Ok, closing as it works.
