### ISSUE TITLE
Can not subscribe RSS with Brief

### ISSUE THREAD

**Issue by hyper2002** [brief-rss/brief#394]
For some part of rss channels f.e ebay , allegro search results - I can not add them to subscribe with Brief .
There is no such option:
![obraz](https://user-images.githubusercontent.com/37906986/45952383-243bc100-c007-11e8-8f4b-956d8dcc3cf3.png)

**Comment by adimit** [comment]
I've got the same issue with this RSS feed:

https://www.questionablecontent.net/QCRSS.xml

The option to subscribe did not show up. Notice there's a Brief icon in the address bar. Clicking it does subscribe to the feed, but the feed remains empty. I'm assuming Brief/Firefox can't parse the feed correctly?

![feed](https://user-images.githubusercontent.com/15893/46904003-d3203e00-cedd-11e8-9203-db874aacc88b.png)

**Comment by tuomosipola** [comment]
Same problem with Freakonomics feed: 

https://rss.art19.com/freakonomics-radio

Not showing in the Firefox subscription list but I can click the Brief icon in the address bar. I can subscribe to this with the soon-to-be-deprecated Firefox RSS system. I'm guessing that Brief cannot parse this feed. I've encountered a couple others.

**Comment by jtdor** [comment]
Issue #343 mentions that an extension adding itself to the “Subscribe to this feed using …” list is not possible anymore since FF 60 or so (and apparently never should have been possible):

> Correct, it's not in that list and, likely, will never be there [again]. Extensions have no access to it since Firefox 60. Please use the Brief icon in the address bar (it's even animated to be more visible).
> https://github.com/brief-rss/brief/issues/343#issuecomment-396304298

**Comment by adimit** [comment]
That solves the issue of subscribing to a feed, but it does not solve the issue that the feed does not actually work after subscribing to it.

**Comment by tanriol** [comment]
See #343/#412 (subscribing), #411 (Freakonomics) and #414 (QC RSS). Closing in favour of specific bugs.

**Comment by onesolo** [comment]
Also cannot subscribe to this feed on 2.5.9
https://www.neowin.net/news/rss/software/

It adds the feed but I get a moz-extension://(some weird long number) on the bottom of the feed list in Brief and doesn't show any headline
