### ISSUE TITLE
SIMPLE QUESTIONS

### ISSUE THREAD

**Issue by EstherMoellman** [brief-rss/brief#396]
Hi,

First, thank you for Brief!

Please, I have simple questions:

1) I read the FAQ, Wiki etc, but is not clear to me if I can customize Brief in order to work with a 3-pane layout. Can I do that? With CSS or etc?

2) Can I create a Dark Theme for Brief at userContent.css?

If both answers are "yes", please, can anyone help me to customize Brief, in order to create a 3-pane layout (feeds, titles, articles), with a Dark Theme?

Thank you in advance!

**Comment by bb84000** [comment]
Hello,

Please go to issue 326 : https://github.com/brief-rss/brief/issues/326
You will find dark theme examples

bb

**Comment by EstherMoellman** [comment]
> 
> 
> Hello,
> 
> Please go to issue #326
> You will find dark theme examples
> 
> bb

Thanks @bb84000 !
Very nice dark theme. I loved it.

I apologize in advance for my ignorance, but please let me ask you: Is there a way to configure Brief in order to use a 3-pane layout? (feeds, titles, articles)?

Thank you once again!

**Comment by tanriol** [comment]
No way to have a 3-pane layout for now. May be possible to add it, but definitely not a priority right now.
