### ISSUE TITLE
Collapsing a folder

### ISSUE THREAD

**Issue by Freudentaumel** [brief-rss/brief#399]
I can't collapse the Comments folder.
What can I do?

**Comment by Freudentaumel** [comment]
Unfortunately, this problem still exists. How can I solve it?

**Comment by Ngamer01** [comment]
You're going to need to provide more information including screenshots.  Also what Firefox version are you using, what platform are you using Brief on, etc.

**Comment by Freudentaumel** [comment]
Screenshot: https://www.directupload.net/file/d/5300/549nyhf7_png.htm
I am using Firefox 64.0
What do you mean with "platform"?
What other information do you need?

**Comment by Ngamer01** [comment]
Platform is what OS are you using.  Windows 10?  Mac?  Some variation of Linux?

**Comment by Freudentaumel** [comment]
Thank you for your quick answer.

My platform is Windows 10 Home.

**Comment by 92Julian** [comment]
Those feeds are outside the folder, feed in folders have indentation.
Press "Organize" and move the feeds to the folder.

**Comment by Freudentaumel** [comment]
When I click on "Organize" and try to move the feeds into the folder, they always appear above the folder name "Comments" in the normal feed list.

What am I possibly doing wrong?

**Comment by 92Julian** [comment]
Feeds should be in between the folder title and the ellipsis.
![captura de pantalla de 2018-12-13 14-48-59](https://user-images.githubusercontent.com/25293942/49957728-79d98880-fee7-11e8-9d6d-2b89e5c7527e.png)

**Comment by Freudentaumel** [comment]
https://www.directupload.net/file/d/5300/xhd3ljtr_png.htm

Aren't they? Or do I misunderstand you?

**Comment by 92Julian** [comment]
The "Kommentare" folder is closed, click in the arrow to open it and then move the feeds inside.

**Comment by Freudentaumel** [comment]
Hello, 92Julian,

Now it's worked. That was under the proverb "What lasts long, finally lasts well".

I thank you for your help
Gerhard
