### ISSUE TITLE
Adding a new feed

### ISSUE THREAD

**Issue by Pienamics** [brief-rss/brief#401]
How do I add a feed?  It used to be by going to the feed's page then subscribing via a dropdown at the top of the page.  Now the dropdown only contains "Live Bookmarks"  Brief has disappeared and there's no other way to add a single feed.  I've attached a screen shot.

FF 63.0.1
Brief 2.5.8
Mac El Capitan

[Screen Shot 2018-11-03 at 19.20.20.pdf](https://github.com/brief-rss/brief/files/2545286/Screen.Shot.2018-11-03.at.19.20.20.pdf)

**Comment by harry-dresden** [comment]
I'm having the same problem. I tried using Organize to add a feed without success.

FF 63.0
Win 7 Pro
Brief 2.5.8

**Comment by jakobon** [comment]
I noticed the exact same behavior change during the last few weeks.
When subscribing using the RSS icon on the webpage or pressing the RSS icon in the browser address field, not I suddenly only have "Live Bookmarks" and no longer able to select "Brief".

**Comment by Pienamics** [comment]
The behaviour is odd. If you open an RSS feed which works (i.e not a broken or empty one) and click on the "Brief" icon in the address bar then although the option to use Brief isn't offered in the drop-down, the feed will appear in Brief.

**Comment by jakobon** [comment]
I have managed to add some RSS feeds by clicking on the "Brief" icon in the address bar, but for some reason a few does not work. 
Previously, when I could select "Brief" in the "Subscribe to this feed using" option, this always worked - at least until the "Brief" option disappeared. 
One of the feeds I cannot get added using the "Brief" icon is this: <https://blogs.technet.microsoft.com/ptsblog/>, but there doesn't seem to be a difference from other blogs. 
Very odd indeed.

**Comment by Revisor** [comment]
Ok, so FF 64 removed Live Bookmarks and feeds now don't display as a page, but as a code. The Brief icon in the address bar has disappeared.

How can I subscribe to a feed for a Youtube channel for example?

Channel URL: https://www.youtube.com/channel/UCwpmyAEOxIFmiXHFk4XbLMA
No Brief icon appears in the address bar, because I guess Google left all appearance of using open standards such as RSS/Atom a long time ago.

Channel feed URL: https://www.youtube.com/feeds/videos.xml?channel_id=UCebx-TT_kPognZx1nIfnb_g
FF 64 displays it as a code, not as a readable page anymore. No Brief icon appears in the address bar either.

Brief doesn't allow to subscribe to a feed manually, or does it?

How can I subscribe to the above feed?

**Comment by sleek22** [comment]
I use the Livemarks add-on. I add the feed there which just adds a folder at the end of my bookmarks. I then use Livemarkss to export the feed and then I import that feed back into Brief. I then delete the feed from Livemarks or just delete the folder from my bookmarks. It works for most feeds.

https://addons.mozilla.org./en-US/firefox/addon/livemarks/

**Comment by Revisor** [comment]
You brought me to another idea: Create an OPML that just contains the new feeds I want to subscribe to and import them into Brief:

```
<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.0">
	<head>
		<title>Feeds OPML Export</title>
		<dateCreated>Thu Dec 13 2018 10:41:21 GMT+0100 (Central European Standard Time)</dateCreated>
	</head>
	<body>
		<outline text="Skill Up" type="rss" version="RSS" htmlUrl="https://www.youtube.com/channel/UCZ7AeeVbyslLM_8-nVy2B8Q" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCZ7AeeVbyslLM_8-nVy2B8Q"/>
	</body>
</opml>
```

That worked alright, but it is quite complicated to do every time I want to subscribe to a new feed. :)

**Comment by tanriol** [comment]
Some feeds should now work with Brief 2.5.9, some will be re-enabled in the next few versions. Sorry, I've severely underestimated the amount of problems in that area. See #411, #412, #406.

**Comment by Revisor** [comment]
Thank you very much.
