### ISSUE TITLE
does not work in 64 bit version

### ISSUE THREAD

**Issue by Moschkara** [brief-rss/brief#403]
addon does not work in 64 bit version, does not update the news feed.
in the 32 bit version everything is ok

**Comment by tanriol** [comment]
Could you provide details on your OS and Firefox versions?

**Comment by Moschkara** [comment]
Win 7 64 bit
Firefox 64 bit 64.0

**Comment by tanriol** [comment]
Tested the same configuration and it seems to work for me.

Does Brief show any feeds or nothing at all?

Does https://firefox-storage-test.glitch.me/ show anything bad?

**Comment by tanriol** [comment]
Closing as never confirmed or reproduced.
