### ISSUE TITLE
Change icon number color

### ISSUE THREAD

**Issue by gabri25ele** [brief-rss/brief#407]
Is possible to change icon numer color?

![icon](https://user-images.githubusercontent.com/33927879/49868408-a3be7c80-fe0d-11e8-80a7-e2a49116b01d.PNG)

grey on black is not the best color scheme for readability

**Comment by gabri25ele** [comment]
I don't know...
Firefox 64 on Windows 10

**Comment by AraldoL** [comment]
Here also White on Grey and OK. Firefox ESR 52 x64 on Win7 x64 with old (non-Quantum) version 2.4.0 of Brief. Sometimes when I restart Firefox its White on Red at first. Then all other Addons with overlay numbers on their icons show also White on Red, no not a Brief issue.
Feedbro which I have installed too (different feeds than Brief) shows his number White on Dark Blue in the same browser. Better contrast than White on Grey.

**Comment by Ngamer01** [comment]
Mozilla changed the default theme for Windows 10 users some time ago and that broke the coloring for Brief's unread number on the extension toolbar icon.  Tanriol has been so swamped with real-life work, but maybe the next Brief release can fix it.  Meanwhile if one is an experienced userChrome.css user, they can figure out what properties the toolbar icon uses and can write a userChrome change for us?

**Comment by sleek22** [comment]
I just did it. Here's the code to place in your userChrome.css

`#brief_mozdev_org-browser-action .toolbarbutton-badge {background-color: white !important}`

**Comment by gabri25ele** [comment]
not work for me

![cattura](https://user-images.githubusercontent.com/33927879/49993103-24a08400-ff86-11e8-847b-1c6ab27ab8ed.PNG)

**Comment by gabri25ele** [comment]
not work for me

![cattura](https://user-images.githubusercontent.com/33927879/49993189-5fa2b780-ff86-11e8-898d-1ed3e0104236.PNG)

**Comment by sleek22** [comment]
gabri25ele,

You have something weird in the way your code is listed. A green color means that part of the code is a comment and not active. Also, the red in tab color means that you haven't hit save yet.

**Comment by Freudentaumel** [comment]
I´ve tried this code

`#brief_mozdev_org-browser-action .toolbarbutton-badge {background-color: white !important}
`
but it is only the same as before

![grafik](https://user-images.githubusercontent.com/31142385/50048406-60913180-00cb-11e9-884d-3ed5ee12b8b7.png)

**Comment by sleek22** [comment]
Freudentaumel,

Just to be clear, this code has to be in your userChrome.css file.

![pic 2](https://user-images.githubusercontent.com/4625685/50048732-1e4afe80-0091-11e9-8ebd-8d495c501eb1.png)

**Comment by Freudentaumel** [comment]
Thank you for pointing out that the code does not have to be inserted in the Brief settings page, but in the userChrome.css file.

I also use Firefox 64 on Windows 10.

**Comment by sleek22** [comment]
Freudentaumel,

So, did it work for you?

**Comment by gabri25ele** [comment]
I change the line and now it works

**Comment by Freudentaumel** [comment]
Hi sleek,

that is correct - it works for me.

**Comment by tanriol** [comment]
How about semi-transparent like this?
![screenshot_20181223_034204](https://user-images.githubusercontent.com/1027034/50379801-c863f100-0664-11e9-8072-f4f5e2034702.png)

**Comment by 92Julian** [comment]
> How about semi-transparent like this?
> ![screenshot_20181223_034204](https://user-images.githubusercontent.com/1027034/50379801-c863f100-0664-11e9-8072-f4f5e2034702.png)

I prefer #666666 background and #FFFFFF numbers because it is consistent with uBlock Origin.
