### ISSUE TITLE
Firefox 64 downloads some feeds instead of subscribing

### ISSUE THREAD

**Issue by slrslr** [brief-rss/brief#411]
Hello,

Brief 2.5.8 do not understands the RSS on this page: https://csirt.cz/news/security/
It do not offer subscribbing.
Any idea what is wrong? Can this be supported?

Web browser (Firefox 64) on Windows 7 offer me to download file and the file content starts with:
`<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"><channel><title>...`

**Comment by onesolo** [comment]
Is this why I also can't subscribe this feed here:
https://www.neowin.net/news/rss/software/

Can this be fixed? Hope so...

**Comment by tanriol** [comment]
@onesolo There's no preview for your feed (#412), but the Brief subscribe button is active in the address bar and you can subscribe with it.
