### ISSUE TITLE
There are no feed previews in Firefox 64

### ISSUE THREAD

**Issue by Smile4ever** [brief-rss/brief#412]
http://www.pusheen.info/rss is not recognised as a feed, but http://www.pusheen.info shows the brief icon in the address bar. What's happening here?

**Comment by 92Julian** [comment]
You can integrate [RSSPreview](https://github.com/aureliendavid/rsspreview) it is licensed under MPL like Brief.

**Comment by 92Julian** [comment]
Related bug: #380

**Comment by 92Julian** [comment]
Now RSSPreview is licensed under the MIT license. If you integrate or add compatibility for RSSPreview this bug and #411 can be fixed.

**Comment by tanriol** [comment]
Preliminary preview implemented in 2d3d5603db6aa6a16a0420a1e2bb729ba7696852 and follow-ups.
