### ISSUE TITLE
Использовать уже существующую открытую вкладку, если нажимать на кнопку аддона.

### ISSUE THREAD

**Issue by popovn** [brief-rss/brief#424]

**Comment by Sxderp** [comment]
Duplicate of #277

**Comment by tanriol** [comment]
Действительно дубликат #277, так что я закрою этот репорт, чтобы не умножать сущности для одного и того же.

@popovn, дублируя вопрос оттуда: имеет ли эта фича смысл с ограничением "только при существовании прикреплённой (pinned) вкладки Brief"?

**Comment by popovn** [comment]
> "только при существовании прикреплённой (pinned) вкладки Brief"?
Я не могу придумать ситуацию, когда может потребоваться открыть кнопкой аддона несколько вкладок, независимо от их состояния.

**Короткий ответ: нет**

**Comment by tanriol** [comment]
У меня бывали ситуации, когда я целенаправленно открывал несколько вкладок с разными активными лентами в разных окнах.

**Comment by popovn** [comment]
**Баг не важный** ибо для себя я его обошел так пока : 
Прилепил вкладку, а кнопку никогда не жму - использую только как маркер что что есть непрочитанное (немного неудобно). 

Если бы на вкладке был такой маркер (это возможно в файрфоксе) - то и кнопку бы убрал.
