### ISSUE TITLE
В букмарках чтото с кнопками непрочитанное/все

### ISSUE THREAD

**Issue by popovn** [brief-rss/brief#426]
кнопок нет - настройка берется из предыдущего экрана (фида / папки )

**Comment by Sxderp** [comment]
The bug is that there is no GUI button to display only unread or read entries when on the bookmarks page. The display is set to whatever the previous page had.

--
After a quick test, I can confirm that the hotkeys still work to toggle the display.

**Comment by tanriol** [comment]
Let's consider this a duplicate of #142. Yeah, weird choice IMO.
