### ISSUE TITLE
Feed empty, but sidebar updating

### ISSUE THREAD

**Issue by TheDancingCode** [brief-rss/brief#427]
Hi,

Since a couple of days Brief is updating the feed entry count in the sidebar but no longer displaying the entries in the main view, with the exception of pages that I bookmarked in the browser.

![Screenshot](https://user-images.githubusercontent.com/25923790/51329983-844eeb00-1a6e-11e9-95fa-c08c1f8c64c1.png)

I'm on Firefox 64.0.2 and Windows 10. The console logs this:
```
Loading failed for the <script> with source ‘moz-extension://2f3552df-48e5-4139-8b25-6324ce751868/scripts/plural-data.js’. brief.xhtml:15:4
Brief: opening database in default storage database.js:135:9
Brief: opened database in default storage database.js:168:9
Brief: 27 feeds in database database.js:306:9
Brief: opened database with 4625 entries database.js:89:9
Use of xml:base attribute is deprecated and will be removed soon. Please remove any use of it. feedview.js:963:8
```

**Comment by Sxderp** [comment]
The little star next the "search bar" [1] indicates that you have selected to show only bookmarked items. If you choose one of icons next to it you'll either get all items or only unread items.

[1] Pretty sure searching doesn't work, but that's irrelevant to this issue.

**Comment by TheDancingCode** [comment]
Thank you. Silly me.
