### ISSUE TITLE
Export bookmarked item from one machine to an other 

### ISSUE THREAD

**Issue by Patclash** [brief-rss/brief#438]
Where are the bookmarked item stored ?
So I can save them and restore them in a new pc

**Comment by n8v8R** [comment]
feeds are no longer bookmarked. For import/export of feeds use

![im_export feeds](https://user-images.githubusercontent.com/13611490/57068282-90834f00-6cd1-11e9-9c29-989a81847921.png)

**Comment by MorganChampion** [comment]
So how do I import feeds from Feedbro?


"You can't dislike a 14-second video and decide as a result you're entitled to kill the American ambassador.
It's not acceptable. It just has to stop."
Salman Rushdie, The Listener, October 13-19 2012, pg 18.
 

    On Thursday, 2 May 2019, 9:58:27 PM NZST, n8v8R <notifications@github.com> wrote:  
 
 
feeds are no longer bookmarked. For import/export of feeds use

**Comment by n8v8R** [comment]
According to the Feedbro description

> Can export feed subscriptions to an OPML file

-> Export from Feebro and import that OPML file into Brief

**Comment by tanriol** [comment]
Closing as the question seems to be resolved. Please reopen if there's still a question.
