### ISSUE TITLE
post 66.0.1 and 66.0.2 upgrades feeds are gone...

### ISSUE THREAD

**Issue by harry-dresden** [brief-rss/brief#439]
... on my Win 7 ultimate system.  Read through FF 61.0.1 - Brief ceased working and all feeds gone #377 with low comprehension, but the last post mentioned making a "new profile." How do you do that? What sort of profile? TIA, HD

**Comment by n8v8R** [comment]
new FF profile. 

https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by tanriol** [comment]
Not enough data here to actually do anything. For better error reporting see #527.
