### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by mmatous** [brief-rss/brief#445]
AMO lists Brief under MPL 1.1 while the LICENSE file mentions MPL 2.0. Please update either (probably AMO) accordingly.

**Comment by tanriol** [comment]
Looks like it's impossible to update license for an already published version on AMO. Will try to publish the next version as MPL 2.0.

**Comment by tanriol** [comment]
The problem turned out to be a lack of permissions. Fixed now for the current and future versions.

**Comment by ancestorak** [comment]
I've adjusted the license on AMO. Thanks for pointing it out!
