### ISSUE TITLE
FireFox just disabled Brief

### ISSUE THREAD

**Issue by VillageCatDad** [brief-rss/brief#447]
Just lost Brief.  FF says "Brief cannot be verified for use in Firefox and has been disabled."  WTFO????  I lost all of my Add-ons, so this is on the FF side, not the Brief side.  I've read a bunch of articles on this, and it appears to be something related to a FF cyper-security initiative.  Regardless -- I want Brief back!!

**Comment by MrPiethon** [comment]
Was there a firefox update? Mines still works perfectly

**Comment by VillageCatDad** [comment]
I'm running FF 66.0.3 on MacOS 10.14.4.  When I click on FF "Unsupported Extensions" on Add-Ons tab, FF has disabled Brief, Adblock Plus, Dark Mode, and DuckDuckGo Privacy Extensions.  There is a "more info" link, and it describes a 2017 WebExtensions API migration, which, according to Brief GitHub comments, was done a long time ago.  So not sure what is going on!  Google search shows lots of other FF Extensions just got cut off too.

**Comment by 92Julian** [comment]
This is a Mozilla bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by tanriol** [comment]
This should be fixed now on Mozilla's side, closing.
