### ISSUE TITLE
Brief not working with FPI enabled

### ISSUE THREAD

**Issue by n8v8R** [brief-rss/brief#449]
FF 68.0a1 (2019-05-11) (64-bit) on W10 and Brief stopped working. Feeds are not being refreshed any more and pressing Refresh in the Brief pane does not yield any action.

Browser console reports

> Loading failed for the <script> with source “moz-extension://9c528316-7a48-43a6-8343-86d116baf128/scripts/plural-data.js”. brief.xhtml:15:4
> Brief: opening database in default storage database.js:135:17
> Brief: opened database in default storage database.js:168:17
> Brief: 77 feeds in database database.js:306:17
> Brief: opened database with 4193 entries database.js:89:17
> Array.forEach is deprecated; use Array.prototype.forEach instead feedlist.js:9:11
> Array.concat is deprecated; use Array.prototype.concat instead database.js:1422:40

**Comment by tanriol** [comment]
Does not reproduce for me on the same Nightly (the feeds update successfully). The messages look like normal messages (nothing that should impact anything) from the Brief tab console.

Could you please open `about:debugging`, find Brief and open its debug console, ensure it refers to `_generated_background_page` (or switch to it if needed) and check for error messages there?

**Comment by n8v8R** [comment]
> Does not reproduce for me on the same Nightly

Is this on current W10 or Linux?
___
The debugging log is showing plenty of

>  Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 21 background-index.js:1
>     createSyncMiddleware moz-extension://fd885cb3-eecb-4a79-a774-f9dcbec1e680/background-index.js:1

Other errors

>  Error: Invalid tab ID: 15 ExtensionUtils.jsm
>  Promise resolved after context unloaded prefs.js:37
>     set moz-extension://9c528316-7a48-43a6-8343-86d116baf128/scripts/prefs.js:37

and some warnings

>  The ‘storage’ attribute in options passed to indexedDB.open is deprecated and will soon be removed. To get persistent storage, please use navigator.storage.persist() instead. database.js:145:31
> Stylesheets without CSSOM changes reparsed to check for errors. Refresh the page to also see errors from stylesheets changed from CSSOM and from style attributes.

**Comment by tanriol** [comment]
> Is this on current W10 or Linux?

Linux, I don't have current W10 at hand.

> background-index.js

Not Brief's bug, it seems, Brief does not have a page with this name.

> Promise resolved after context unloaded prefs.js:37

This actually looks like Brief, and the line refers to a pref update... no idea which pref, but this should not be critical.

> The ‘storage’ attribute in options passed to indexedDB.open is deprecated

Known and harmless.

By the way, in the console (any of these two) does `await browser.storage.local.get()` return immediately with some value, print an error or do something else?

It may be a good idea to clear this console, disable-and-reenable Brief with the addon manager (but not reinstall!) and check for messages. If the message about `prefs.js` is still displayed, the lines before (specifically the pref being updated) may be of interest too.

**Comment by n8v8R** [comment]
> Linux, I don't have current W10 at hand.

Suppose have to see and wait whether/when other users on the W10 platform might be hit.
___
> By the way, in the console (any of these two) does `await browser.storage.local.get()` return immediately with some value, print an error or do something else?

Nothing of that sort
___
> If the message about `prefs.js` is still displayed

Did not appear again.

**Comment by tanriol** [comment]
Checked on a fully updated W10 VM in a new Nightly profile, no problems either.

> > By the way, in the console (any of these two) does `await browser.storage.local.get()` return immediately with some value, print an error or do something else?
> 
> Nothing of that sort

Do you mean no reply at all, not even something like `Object {  }`, not even `undefined`? That would be really weird, especially if the "opened database with (number) entries" message is displayed too...

**Comment by tanriol** [comment]
One more question: do you have any non-standard / paranoid settings around security / privacy / cookies?

**Comment by n8v8R** [comment]
> Checked on a fully updated W10 VM in a new Nightly profile, no problems either.

That might be still a different scenario then updating N on an existing profile - that what happened my end, either after last night's update or this morning. Nothing else done to the browser.
Unfortunately there is no roll-back option...

**Just noticed that the Brief icon in the URL bar for subscribing to feeds is gone too!**
___
For sake of good order ran https://firefox-storage-test.glitch.me

> Specific Subsystem Statuses:
> 
> LocalStorage
>     Good: Totally Working. (fullyOperational)
> QuotaManager
>     Good: Totally Working. (fullyOperational)
> IndexedDB
>     Good: Totally Working. (fullyOperational)
> Cache API
>     Bad: Totally Broken. (fullyBroken)
> 
> Debug Info:
> 
> caches is not defined
> 
> {
>   "v": 1,
>   "curVersion": 66,
>   "prevVersion": 0,
>   "ls": {},
>   "qm": {
>     "lastWorkedIn": 66
>   },
>   "idb": {
>     "persistentCreatedIn": 66,
>     "persistentLastOpenedIn": 66,
>     "clearDetectedIn": 0
>   },
>   "cache": {
>     "firstCacheCreatedIn": 0,
>     "unpaddedOpaqueCreatedIn": 0,
>     "paddedOpaqueCreatedIn": 0
>   }
> }
____
> Do you mean no reply at all, not even something like `Object { }`, not even `undefined`?

Yes, that is what I mean.
____
> One more question: do you have any non-standard / paranoid settings around security / privacy / cookies?

Indeed, but that was no issue for brief until yesterday. I am not going to list all of them but for sure fingerprinting resistance and first party isolation are on by any means.
____
Hmm, seems the culprit causing is actually this WX https://github.com/sereneblue/chameleon

**Comment by tanriol** [comment]
That's an interesting result. If you find out specifically which setting causes the problem please share so that it can be documented or reported to Mozilla if this is actually a Firefox problem.

**Comment by n8v8R** [comment]
Have tried various settings in Chameleon but that did not make a difference, even with restarting the browser in between.
Only disabling Chameleon and restarting the browser revives Brief to a working state, just disabling Chameleon does not.

Thus I suspect Chameleon not being the culprit but the code change in the browser somehow causing this.

Could not reproduce the issue on FF current, beta and developer.

Perhaps Mozilla will rectify the code causing this until the browser reaches beta. Will notify the developer of Chameleon nonetheless.

**Comment by n8v8R** [comment]
Turns out that Chameleon is not causing this but having First Party Isolation enabled (requires browser restart for change to take effect).

I was able to reproduce this on the existing FF profile as well as on a new one.

From what I have been gathering there are some changes to the FPI code in the current Nightly branch.

**Comment by tanriol** [comment]
Reproduced, `mozregression` points at [bug 1330467](https://bugzilla.mozilla.org/show_bug.cgi?id=1330467) permissions-in-FPI rework.

**Comment by n8v8R** [comment]
For now Mozilla has reopened the bug and backed out the code, thus for the time being Brief is working again. 

Perhaps best to keep an eye on further developments, least when it gets into beta

**Comment by n8v8R** [comment]
Mozilla reinstated the code with Nightly 69.0a1 (2019-05-27) and FPI breaks Brief

**Comment by n8v8R** [comment]
commits with FX (Nightly) changeset3fa65bda1e506a314ea90d936f763c7e840ab98a would appear of having solved the issue, hopefully code will be uplifted soon to beta and current.
