### ISSUE TITLE
FF Nightly - settings unreadable with dark W10 theme

### ISSUE THREAD

**Issue by n8v8R** [brief-rss/brief#450]
In the current FF Nightly trunk the default theme adds support for the OS (W10) colour scheme and if latter being dark the Brief settings are not readable.

68.0a1 (2019-05-13) (64-bit) on W10

![theme settings](https://user-images.githubusercontent.com/13611490/57692791-f5329800-7647-11e9-883f-e219e7cd4f0d.png)

![breif settings](https://user-images.githubusercontent.com/13611490/57692813-011e5a00-7648-11e9-8694-46516669aac4.png)

**Comment by tanriol** [comment]
Looks like this is a Nightly-only experiment for now, and the problem [is known](https://bugzilla.mozilla.org/show_bug.cgi?id=1544212). The easiest way out would be to force the background to light.

**Comment by n8v8R** [comment]
Sure, will see whether it makes into beta/stable at some point (which I trust it will), by which perhaps Mozilla will figured how to reverse the contrast for WX settings.

Most other WX being utilized on this node provide their own settings page.

**Comment by n8v8R** [comment]
M landed in FF 68 a new setting `extensions.htmlaboutaddons.enabled` which solves the matter

![wx setting](https://user-images.githubusercontent.com/13611490/59257663-a96b1280-8c36-11e9-9a63-a922401eeb24.png)
