### ISSUE TITLE
Display of unread posts

### ISSUE THREAD

**Issue by Freudentaumel** [brief-rss/brief#456]
Since the update to version 2.6.0b1 the unread contributions are missing next to the letter symbol. The field for the display remains white = empty.

**Comment by tanriol** [comment]
Sorry, I don't understand what part of the UI you're talking about. Could you please provide a screenshot and/or a better description?

**Comment by Freudentaumel** [comment]
I hope this screenshot makes my concern clear:

https://www.directupload.net/file/d/5469/qxwx7iae_png.htm

**Comment by tanriol** [comment]
What's your browser/OS version? Do you have any special settings overriding the colors? Brief tries to set background color to dark gray (`#666666`), and Firefox matches that with white text. For some reason looks like it's white on white in your case, but I don't know why.

**Comment by Freudentaumel** [comment]
> What's your browser/OS version?
 Windows 10 Home

> Do you have any special settings overriding the colors?
Since the actual update the color was red.

I think I made a corresponding change in the userchrome.css in my Firefox profile at the time. Unfortunately I can't find the code anymore. What should it be? I could send you a screenshot or a copy.

**Comment by tanriol** [comment]
There's probably something that mentions `.toolbarbutton-badge` and possibly `#brief_mozdev_org-browser-action` (and `background-color`), like in #407 comments.

**Comment by Freudentaumel** [comment]
I have only found this code:

**#brief_mozdev_org-browser-action .toolbarbutton-badge {background-color: white
 !important}**

**Comment by tanriol** [comment]
Yeah, that's it. Removing it or commenting it out and restarting Firefox should return Brief's badge to the standard settings.

**Comment by Freudentaumel** [comment]
What means "commenting it out" in detail and how can I make sure that the display of new feeds is red?

**Comment by tanriol** [comment]
You can surround the code in `/* the code goes here */` so that it does not affect anything. What do you want to be red?

**Comment by Freudentaumel** [comment]
> What do you want to be red?

The number in the white box next to the letter icon that indicates the number of new feeds.

In which color is this number displayed in the default settings?

**Comment by tanriol** [comment]
In the default settings it's white on gray.
![Screenshot_20190601_014542](https://user-images.githubusercontent.com/1027034/58738559-fd901e80-840e-11e9-8c5a-dc728fe2e872.png)

**Comment by Freudentaumel** [comment]
Thank you for helping, Denis.
