### ISSUE TITLE
Background js page fails to initialize

### ISSUE THREAD

**Issue by Sxderp** [brief-rss/brief#458]
I'm guessing Mozilla changed something. The last time it was successful was sometime in April 2019. I know this because my feeds stopped updating and therefore there are no new entries.

Current Firefox : 67.0 (issue started occurring before this)
Current Brief: 2.6.0b2

The brief version isn't particularly relevant as the code that seems to be causing issue was committed May 2018.

Somewhat useful info before I begin: When looking at the "Storage" tab in the debugging window for Brief I have two indexedDB entries. One in 'brief (default)' and 'brief (persistent)'. The persistent one is completely empty (I'm pretty sure that's intended).

Background init reaches [line 91](https://github.com/brief-rss/brief/blob/142e2c62ddcb884dae8dcd365de6808960396c8a/background.js#L91) where it tries to initialize the database. At [line 71](https://github.com/brief-rss/brief/blob/142e2c62ddcb884dae8dcd365de6808960396c8a/modules/database.js#L71) of the DB init we check if the previous 'persistent' db has a version greater than 0. For some reason mine has a version of 1 (even though it's empty) and the check passes. Right after a transaction on the database is [attempted](https://github.com/brief-rss/brief/blob/142e2c62ddcb884dae8dcd365de6808960396c8a/modules/database.js#L1476). However, this fails with a 'NotFoundError' [1] presumably because nothing exists in my 'persistent' database.

I haven't tried it but I'm pretty sure if I just delete the 'persistent' database this issue will resolve itself (database should then have a version of 0). But I figured I should make the report to bring this awkward wedge to attention.

[1] NotFoundError: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened.

**Comment by tanriol** [comment]
Wow, thank you for a good catch!

As soon as I looked for this problem by opening the Storage tab it appeared. Looks like this is a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1556274) where opening the Storage tab causes the "non-existing" database to appear with version 1.

**Comment by tanriol** [comment]
This can also be the root reason behind problems with feeds not updating at all like #395, #391, #376, #375 and maybe others.
