### ISSUE TITLE
All RSS items are suddenly from 2018

### ISSUE THREAD

**Issue by AlexHarrowell** [brief-rss/brief#463]
This is really strange but that's what it is - perhaps after today's update? I opened my feeds and started reading and discovered that everything was from May 2018. It's as if Brief has rolled back to the state of 24th May 2018.

**Comment by tanriol** [comment]
Hmm... sounds weird. If you do know that, did Firefox update your Brief between May 30th and June 29th? If auto-update is on, the latest update should have been from 2.6.0b3 to 2.6.0 final, which did not contain anything of risk IIRC.

**Comment by AlexHarrowell** [comment]
Sorry about this. I had somehow turned "show only bookmarks" on and somehow I had accidentally bookmarked a ton of stuff on the 24th March last year.

Sorry for the noise.

On 1 July 2019 17:47:18 BST, Denis Lisov <notifications@github.com> wrote:
>Hmm... sounds weird. If you do know that, did Firefox update your Brief
>between May 30th and June 29th? If auto-update is on, the latest update
>should have been from 2.6.0b3 to 2.6.0 final, which did not contain
>anything of risk IIRC.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/brief-rss/brief/issues/463#issuecomment-507342305

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tanriol** [comment]
Yes, there was an error fixed in Brief 2.5.6 that could lead to bookmarking lots of entries, sorry about that. Closing this issue as there's no issue to fix now.
