### ISSUE TITLE
Unable to add feed

### ISSUE THREAD

**Issue by sullygirl** [brief-rss/brief#465]
I've added a feed that is not showing up in brief.  Please help!

**Comment by tanriol** [comment]
Could you provide a few more details:
- how did you add it,
- do other feeds work for you (including marking as read and/or updating),
- what's the problematic feed, if you can share that.

**Comment by sullygirl** [comment]
I tried clicking on the RSS link to no avail.  I'm looking to follow certain Supreme Court cases, such as:
https://www.supremecourt.gov/search.aspx?filename=/docket/docketfiles/html/public/18-1269.html
Thanks for any help.

**Comment by tanriol** [comment]
This is a duplicate of #462, already a known problem.

For now you can open the developer tools on the Brief tab with F12, open console and subscribe with a command like the following:
```
Database.addFeeds({url: "https://www.supremecourt.gov/rss/cases/18-1269.xml"})
```
where the address was copied by right-clicking the feed icon and choosing "Copy Link Location".

**Comment by tanriol** [comment]
Duplicate of #462.

**Comment by sullygirl** [comment]
Forgive my inexperience - F12 doesn't open anything for me and I see no option in the Brief tab to add feeds. Is there a user manual somewhere?

**Comment by tanriol** [comment]
This function is not documented, it's an internal one. Going from the Firefox menus, this is called Web Console and can be found in "Web Developer" or "Tools" - "Web Developer".
