### ISSUE TITLE
Brief does not work in Firefox 69 with firstparty.isolate set to 'true'

### ISSUE THREAD

**Issue by lollyP** [brief-rss/brief#472]
In Firefox 69 with firstparty.isolate set to 'true', Brief is unable to import OPML files; firstparty.isolate didn't cause such problems previously.

I'm not sure if this is something that can be fixed, or if the operation of firstparty.isolate is now fundamentally incompatible with this extension.

**Comment by Suprcheese** [comment]
Having the same problem. Very unfortunate...

**Comment by n8v8R** [comment]
dup of https://github.com/brief-rss/brief/issues/449

**Comment by n8v8R** [comment]
according to MOZ  bug https://bugzilla.mozilla.org/show_bug.cgi?id=1554805#c34 the patch fixing the issue will not be backported to FX 69 and 70 and thus only be available as of FX 71

**Comment by tanriol** [comment]
This seems to be fixed in the current versions (except 68 ESR, but I'm really unlikely to invent some novel fix before the ESR switches to 78), so I'm closing it. Feel free to reopen if this is still a problem.
