### ISSUE TITLE
Mac OS Notifications

### ISSUE THREAD

**Issue by mmmunafo** [brief-rss/brief#476]
On Mac OS Catalina 10.15, using Firefox 70.0, the Brief notifications are reported indicating the extension code (like 5686c81f-6320-104a-a677-0f5cf583a2e1) instead its proper name.

**Comment by tanriol** [comment]
The extension UUID is being removed in Firefox 70.0.1 according to [mozilla bug 1577316](https://bugzilla.mozilla.org/show_bug.cgi?id=1577316). Closing as this is not a Brief bug.
