### ISSUE TITLE
No update for a long time

### ISSUE THREAD

**Issue by Freudentaumel** [brief-rss/brief#490]
Hello Brief-Developer,

the add-on has not been updated for nine months now. What are the reasons for this?

In the hope of a soon as possible bigger update I wish you good health

Gerhard

**Comment by Sxderp** [comment]
General reason for lack of updates for projects like these is that it works "well enough". And the maintainer doesn't have the drive or time to fix the minor bits as those minor bits don't affect them.

I don't say this as a demerit to @tanriol . A lot of my projects, both public and private, fall into this state.

**Comment by tanriol** [comment]
Mostly lack of free time and the project kinda working. Still that's not good enough for me and I hope to release the next version in a few weeks.

**Comment by Freudentaumel** [comment]
I would be very happy about that, Denis.

**Comment by Freudentaumel** [comment]
Hello, Denis,

would you be so kind to inform me/us here as soon as you have implemented the update?

Many thanks
Gerhard

**Comment by tanriol** [comment]
I need to at least integrate #484 and one more branch I haven't pushed yet, and fix #492.

**Comment by tanriol** [comment]
There have been new updates, so I'm closing this bug as it does not contain any useful information.
