### ISSUE TITLE
The future of the Add-on Brief

### ISSUE THREAD

**Issue by Freudentaumel** [brief-rss/brief#498]
Hello, Denis,

all in all I have the impression that you are "the last fighter" in the effort to maintain and further develop the add-on.

Is my impression correct or am I wrong?

Best regards
by Gerhard

**Comment by tanriol** [comment]
Brief never really had more than one developer. I came to this project when Adam, the only real developer at that time, could not update Brief for new Firefox versions. So the situation is no better and no worse than it used to be.
Yes, at the moment I'm having problems with time to do things - not only here, but in other areas too. Really hope that's a temporary situation.

**Comment by Freudentaumel** [comment]
Hello, Denis,

can you foresee when you can realize the next update?

Hopeful greeting
by Gerhard

**Comment by tanriol** [comment]
The next update has been released, and I'm closing this issue as there's no specific problem to be solved here (well, apart from me being the only Brief maintainer).

**Comment by Freudenmensch** [comment]
Where can I find the addon now?

**Comment by tanriol** [comment]
As before, on [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/brief/), or here in [the releases section](https://github.com/brief-rss/brief/releases/).
