### ISSUE TITLE
Firefox 79 - Brief no longer auto-trashes items that fail to meet the user's storage criteria in Brief's settings

### ISSUE THREAD

**Issue by Ngamer01** [brief-rss/brief#504]
My user-agent:  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0

After the recent update to Firefox 79, I've happened to notice Brief no longer follows a user's storage settings so it no longer auto-trashes items that fail to meet the storage criteria set in the settings.

Feed to confirm this:  http://www.manatheater.com/seymour.xml

Basically the feed hasn't been updated for quite some time, but it always generates one entry from 2012 that usually would be auto-trashed since I have set a 7-day limit for items to stay stored before they're auto-trashed.

**Comment by Ngamer01** [comment]
I know it's been awhile, but apparently some time ago the auto-trashing began working again, so I couldn't tell you when exactly my issue resolved itself.  So I'll close this as "Resolved - Works for me".  If somebody has issues with the auto-trashing option, this issue can be reopened or a new, up-to-date issue can be filed.

**Comment by tanriol** [comment]
Thank you for reporting that it's working correctly again.
