### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Wombat2018** [brief-rss/brief#522]
Hello,

I wanted to ask when the new version with the fix (https://github.com/brief-rss/brief/issues/517) for sorting the feeds will be released.
The latest release at addons.mozilla.org is dated 29 June, 2019.

I would appreciate an answer.

**Comment by tanriol** [comment]
Will try to release in a few days to fix Brief for Nightly users too.

**Comment by tanriol** [comment]
Brief 2.6.1 has been released.
