### ISSUE TITLE
no more fonctionnal with firefox 127.0a1

### ISSUE THREAD

**Issue by fredmo** [brief-rss/brief#535]
It sounds to be the end.

Brief doesn't refresh the feed on the current nightly 127.0a1.

Good bye Brief, you were a very nice RSS reader.

Thany you.

**Comment by tanriol** [comment]
Confirmed, I do see the problem too. Will check what's going on.

**Comment by tanriol** [comment]
Okay, so I've missed the final removal of `indexedDB.open`'s `openOptions`  variant. Will fix in a couple days at most - I use Brief with Nightly too, so that's not something I could just ignore.

**Comment by tanriol** [comment]
@fredmo Thank you for telling me about Brief being broken in Nightly. Fixed in [b40aa685d](https://github.com/brief-rss/brief/commit/b40aa685da38995d9a803729b282a5706a9de016), released as Brief 2.7.0.

**Comment by fredmo** [comment]
I confirm it's now solved 
Thank you!
