### ISSUE TITLE
Extension homepage URL in the manifest still points to mozdev.org

### ISSUE THREAD

**Issue by KernelLeak** [brief-rss/brief#543]
Looking into Brief's extension options and hence the `manifest.json` in the current `brief@mozdev.org.xpi`, it still says:
```
  "homepage_url": "http://brief.mozdev.org",
```

That site doesn't even resolve anymore - maybe point it to https://github.com/brief-rss/brief instead? (I guess the file name for the extension is also out-of-date-ish, but also a non-issue?)

**Comment by slrslr** [comment]
Firefox ESR, Brief extension, Details tab on "about:addons" page shows http://brief.mozdev.org as a homepage, which is not loading on my end. Brief 2.7.2.

**Comment by tanriol** [comment]
Thanks for reporting, going to fix in the next update.
