### ISSUE TITLE
Titles in page are wrong and duplicating

### ISSUE THREAD

**Issue by FCsean** [brief-rss/brief#548]
Feed is coming from: https://psa.wf/feed/
Checking the data no duplicates in the title to cause the issue, but below is happening.

![1](https://github.com/brief-rss/brief/assets/6689718/6def89ad-4360-49de-82f7-d0173c50086c)

![2](https://github.com/brief-rss/brief/assets/6689718/cdcbb95b-c5fd-496f-84f3-4a4d7d93e0b8)

**Comment by FCsean** [comment]
Was able to reproduce the issue on a freshly installed firefox nightly. So unrelated to old data in db.

Issue seems to only happen on further syncs. On initial sync the issue does not happen.

**Comment by FCsean** [comment]
Hmm might be related to the feed missing guid value.

**Comment by FCsean** [comment]
Closing since issue with the feed itself

**Comment by tanriol** [comment]
I don't see any duplication today, so I assume the feed has been fixed on the server side. Confirmed close.
