### ISSUE TITLE
issue with https login/pw in Rss url

### ISSUE THREAD

**Issue by fredmo** [brief-rss/brief#552]
Well, I would have some difficulty to explain,

I am using firefox nightly :  131.0a1 (2024-09-01) (64 bits) / Windows 11 23h2

I created a personnal rss field with a login/pw in the url :
http://rss_filtred:GoodJob!!@fredericmtest.dynv6.net/rss/www.starwars-universe.com_swu_rss_min_sans_spoilers.xml.xml

I succeed to add it in my field ( with the login/pw :  rss_filtred:GoodJob!! ) in the url 
I edit the url to have the login/pw during the registering.

The articles are presents 1 only time, I mean during the registering all articles are presents , but if I delete all of them (by the setting menu) and I redo the re-fresh, the articles are not downloaded

**Comment by tanriol** [comment]
Brief intentionally does not completely remove feed entries from its database as long as they're present in the feed to ensure they don't come back on refresh. Users generally don't expect entries they've intentionally deleted to reappear on their own.
I've tested that Brief successfully fetches your feed on refresh (thank you for providing a valid username/password pair). Still want to double-check why it does not support adding that feed without changing the URL manually.

Feel free to reopen if Brief does not see new entries in that feed when they are added.
