### ISSUE TITLE
"Recent" rather than "Today"

### ISSUE THREAD

**Issue by olvlvl** [brief-rss/brief#58]
Hi,

Could it be possible to have a "Recent" filter instead of a "Today" filter, that would display the entries of the last 24 Hours ? Because at 0H02, when I click "Today" the list is empty, which is understandable but not helpful.

**Comment by vovkkk** [comment]
I would like this section showing entries from the latest day presented in a data base.
I.e. if there are no today entries, then yesterday ones, then before yesterday, and so forth.

It will make reading old entries more convenient, at least you’ll see exact amount of unread entries for the day which may help with time management, like «20 entries, I can read them before sleep» or «200! nope, will return to it later, doing sth different now».

Speaking of section title (Recent, Latest, whatever) it could be dynamic depending on what day’s entries are presented in it, i.e. Today, Yesterday, Wednesday, …, May 1st, …

**Comment by abrowne** [comment]
It could be called "Past 24 hours".
